unstable_features=true
imports_granularity="Crate"
edition="2018"

group_imports="StdExternalCrate"
reorder_impl_items=true
use_field_init_shorthand=true
wrap_comments=true
format_code_in_doc_comments=true
format_strings=true
normalize_comments=true
normalize_doc_attributes=true
report_fixme="Always"
report_todo="Always"
use_try_shorthand=true

